CREATE DATABASE IF NOT EXISTS SYS_SACNA;
USE SYS_SACNA;

DROP TABLE IF EXISTS events_log;
DROP TABLE IF EXISTS system_data;

CREATE TABLE events_log (
EventID INTEGER(16) PRIMARY KEY AUTO_INCREMENT NOT NULL,
EventTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UserID INTEGER(9) NOT NULL,
EventType INT(1) NOT NULL
);

CREATE TABLE system_data(
DataID INTEGER(16) PRIMARY KEY AUTO_INCREMENT NOT NULL,
DataName VARCHAR(50) NOT NULL UNIQUE,
DataValue VARCHAR(255) NOT NULL);

CREATE DATABASE IF NOT EXISTS OCESACNA;
USE OCESACNA;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS representatives;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS subject_modules;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS pending_subjects;
DROP TABLE IF EXISTS scores;

CREATE TABLE users (
UserID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
UserName CHAR(16) NOT NULL,
Password CHAR(64) NOT NULL,
PasswordHash CHAR(64) NOT NULL,
Rank INT(1) NOT NULL,
State INT(1) NOT NULL);

# Usuario y contraseña predeterminados
INSERT INTO users (`UserName`, `Password`, `PasswordHash`, `Rank`, `State`) VALUES ('OCESACNA', 'GGAOj26ZkvpqXvZRQwDvDA==', 'aLHo6SRMUU0sfOVULLQEmI3p320G2ZsFusmybQol05o=', '1', '1');

CREATE TABLE courses (
CourseID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
Year INT(1) NOT NULL,
GuideID INTEGER(9) NOT NULL,
Mention VARCHAR(100) NOT NULL,
Section CHAR(1) NOT NULL);

CREATE TABLE representatives (
RprsentID INTEGER(16) PRIMARY KEY AUTO_INCREMENT NOT NULL,
FullName VARCHAR(100) NOT NULL,
PhoneNumber CHAR(20) NOT NULL,
Email CHAR(255) NOT NULL);

CREATE TABLE teachers (
TeachID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
FullName VARCHAR(100) NOT NULL);

CREATE TABLE subject_modules (
SbjetModuleID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
Name VARCHAR(100) NOT NULL);

CREATE TABLE subjects (
SubjetID INTEGER(9) PRIMARY KEY NOT NULL,
SbjetModuleID INTEGER(9) NOT NULL,
Name VARCHAR(100) NOT NULL,
TeachID INTEGER(9) NOT NULL,
CourseID INTEGER(9) NOT NULL);

CREATE TABLE students (
StudentID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
Cedula INT(20) NOT NULL UNIQUE,
LastNames VARCHAR(100) NOT NULL,
FirstNames VARCHAR(100) NOT NULL,
Age INT(3) NOT NULL,
Sex INT(1) NOT NULL,
Birthdate DATE NOT NULL,
BirthPlace VARCHAR(100) NOT NULL,
FederalEntty VARCHAR(100) NOT NULL,
Address VARCHAR(100) NOT NULL,
PhoneNumber CHAR(20) NOT NULL,
Email CHAR(255) NOT NULL,
RprsentID INTEGER(16) NOT NULL,
CourseID INTEGER(9) NOT NULL);

CREATE TABLE pending_subjects(
PendingSbjetID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
StudentID INTEGER(9) NOT NULL,
Name VARCHAR(100) NOT NULL
);

CREATE TABLE scores (
ScoreID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
StudentID INTEGER(9) NOT NULL,
SubjetID INTEGER(9) NOT NULL,
First FLOAT NOT NULL,
FirstDef FLOAT NOT NULL,
FirstInas INT NOT NULL,
Second FLOAT NOT NULL,
SecondDef FLOAT NOT NULL,
SecondInas INT NOT NULL,
Third FLOAT NOT NULL,
ThirdDef FLOAT NOT NULL,
ThirdInas INT NOT NULL,
Final FLOAT NOT NULL,
FinalDef FLOAT NOT NULL,
FinalInas INT NOT NULL);

ALTER TABLE courses ADD CONSTRAINT courses_GuideId_teachers_TeachID FOREIGN KEY (GuideID) REFERENCES teachers(TeachID);
ALTER TABLE subjects ADD CONSTRAINT subjects_SbjetModuleID_subject_modules_SbjetModuleID FOREIGN KEY (SbjetModuleID) REFERENCES subject_modules(SbjetModuleID);
ALTER TABLE subjects ADD CONSTRAINT subjects_TeachID_teachers_TeachID FOREIGN KEY (TeachID) REFERENCES teachers(TeachID);
ALTER TABLE subjects ADD CONSTRAINT subjects_CourseID_courses_CourseID FOREIGN KEY (CourseID) REFERENCES courses(CourseID);
ALTER TABLE students ADD CONSTRAINT students_RprsentID_representatives_RprsentID FOREIGN KEY (RprsentID) REFERENCES representatives(RprsentID);
ALTER TABLE students ADD CONSTRAINT students_CourseID_courses_CourseID FOREIGN KEY (CourseID) REFERENCES courses(CourseID);
ALTER TABLE pending_subjects ADD CONSTRAINT pending_subjects_StudentID_students_StudentID FOREIGN KEY (StudentID) REFERENCES students(StudentID);
ALTER TABLE scores ADD CONSTRAINT scores_StudentID_students_StudentID FOREIGN KEY (StudentID) REFERENCES students(StudentID);
ALTER TABLE scores ADD CONSTRAINT scores_SubjetID_subjects_SubjetID FOREIGN KEY (SubjetID) REFERENCES subjects(SubjetID);